requires:
  - pypi-mobans-pkg==0.0.2
configuration:
  template_dir:
  - "pypi-mobans-pkg:templates"
  - ".moban.d"
  configuration: snapshot-selenium.yml
targets:
  - README.rst: CUSTOM_README.rst.jj2
  - setup.py: custom_setup.py.jj2
  - requirements.txt: requirements.txt.jj2
  - "tests/requirements.txt": "tests/custom_requirements.txt.jj2"
  - "docs/source/conf.py": "docs/conf.py_t"
  - test.sh: test.script.jj2
  - "snapshot_selenium/_version.py": "_version.py.jj2"
  - .gitignore: gitignore.jj2
  - .travis.yml: travis.yml.jj2
  - Pipfile: Pipfile.jj2